### PR TITLE
Added Portuguese translation

### PR DESCRIPTION
**Pull request by smarquespt**

### CODE REVIEW

**Comment by Kuci** [comment]
Hello, @smarquespt. Thank you for your contribution. Please, remove all the strings marked with translatable="false" because these are not meant to be reused. Otherwise, your commit seems good and I will merge it as soon as you fulfill my request.

**Comment by smarquespt** [comment]
@Kuci 

Please check if it´s ok for you.

Regards

**Comment by Kuci** [comment]
@smarquespt, you did not remove trailing newlines after the strings. Because we want to keep the sources clean, please, remove these unnecessary newlines.

**Comment by Kuci** [comment]
Great. Now rebase all three commits into a single one with the message 'Add Portuguese translation' and it is good to go.

**Comment by smarquespt** [comment]
I´m trying to but I can´t. Can you tell me the commands?

**Comment by Kuci** [comment]
In this case I would just soft reset to the first commit and then just amend and force push.

**Comment by Kuci** [comment]
Please, use 'Add Portuguese translation' as the commit message.

**Comment by Kuci** [comment]
Well, I had some time so I have done it myself. Except changing the commit message I had to remove several whitespaces which I had not noticed before.

Once again, thank you for your contribution.

**Pull request closed without merging**
