### PR TITLE
Added support to Android 6.0

### PR DESCRIPTION
**Pull request by KashifAnwaar**
Added support to Android 6.0 using the quick solution mentioned in #37 . after performing regular clean (which cleans external cache) it'll take to the cache settings to clear internal cache.

### CODE REVIEW

**Comment by Kuci** [comment]
This actually doesn't add support for Android 6.0. Look, Android 6.0 Settings app can clean all the cache, so our app is deprecated now. Let's just let it die.

**Comment by KashifAnwaar** [comment]
Okay can you please tell me how many people are visiting your app in play store daily as of now? which can be seen in User Acquisition section.

Thank you.

**Comment by Kuci** [comment]
Around 500 people a day. Why are you asking ?

**Comment by KashifAnwaar** [comment]
Beacause you said let it die.

**Pull request closed without merging**
